<?php
require_once __DIR__.DIRECTORY_SEPARATOR.'BX'.DIRECTORY_SEPARATOR.'Test.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'BX'.DIRECTORY_SEPARATOR.'DBTest.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'BX'.DIRECTORY_SEPARATOR.'TestTable.php';
